# Generated by Django 4.2 on 2023-04-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('ups_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
