# Generated by Django 4.2 on 2023-04-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
