# Generated by Django 4.2 on 2023-04-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='amazon.product'),
        ),
        migrations.CreateModel(
            name='placeOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.placeorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('truck_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('cart', 'Cart'), ('packing', 'Packing'), ('packed', 'Packed'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], max_length=20)),
                ('note', models.TextField(null=True)),
                ('wh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='amazon.order'),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='items',
            field=models.ManyToManyField(blank=True, through='amazon.placeOrderItem', to='amazon.product'),
        ),
    ]
