# Generated by Django 4.2 on 2023-04-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_warehouse_alter_orderitem_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
