# Generated by Django 4.2 on 2023-04-28 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_orders_wh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='wh_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.warehouse'),
        ),
    ]
