# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_web.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import world_amazon_pb2 as world__amazon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='amazon_web.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61mazon_web.proto\x1a\x12world_amazon.proto\"$\n\x05order\x12\x1b\n\x08products\x18\x01 \x03(\x0b\x32\t.AProduct')
  ,
  dependencies=[world__amazon__pb2.DESCRIPTOR,])




_ORDER = _descriptor.Descriptor(
  name='order',
  full_name='order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='products', full_name='order.products', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=76,
)

_ORDER.fields_by_name['products'].message_type = world__amazon__pb2._APRODUCT
DESCRIPTOR.message_types_by_name['order'] = _ORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

order = _reflection.GeneratedProtocolMessageType('order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'amazon_web_pb2'
  # @@protoc_insertion_point(class_scope:order)
  ))
_sym_db.RegisterMessage(order)


# @@protoc_insertion_point(module_scope)
